version: '3.0'
services:
  fire:
    image: local/fire
    build: ./fire
    ports:
      - 5000:80

  igniter:
    image: local/igniter
    build: ./igniter
    links:
      - fire

  prometheus:
    image: local/prometheus
    build: ./prometheus
    ports:
      - 9090:9090
    links:
      - fire
    volumes:
      - prometheus_data:/data
    command: -storage.local.path=/data

volumes:
  prometheus_data:
